/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
import { ContractArtifact } from 'ethereum-types';

// 使用 Hardhat 编译的 artifacts
import * as DefaultPoolOperator from '../artifacts/contracts/src/DefaultPoolOperator.sol/DefaultPoolOperator.json';
import * as ISablier from '../artifacts/contracts/external/ISablier.sol/ISablier.json';
import * as IStaking from '../artifacts/contracts/src/IStaking.sol/IStaking.json';
import * as IZrxTreasury from '../artifacts/contracts/src/IZrxTreasury.sol/IZrxTreasury.json';
import * as ZrxTreasury from '../artifacts/contracts/src/ZrxTreasury.sol/ZrxTreasury.json';
import * as DummyERC20Token from '../artifacts/contracts/src/DummyERC20Token.sol/DummyERC20Token.json';

export const artifacts = {
    ISablier: ISablier as any,
    DefaultPoolOperator: DefaultPoolOperator as any,
    IStaking: IStaking as any,
    IZrxTreasury: IZrxTreasury as any,
    ZrxTreasury: ZrxTreasury as any,
    DummyERC20Token: DummyERC20Token as any,
};

// 为兼容 @0x/contracts-erc20 格式提供单独的导出
export { artifacts as erc20Artifacts };
