/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
import { ContractArtifact } from 'ethereum-types';

// 从 generated-wrappers 目录导入编译好的 artifacts
// 这些是原始的 0x Protocol 格式 artifacts，兼容 Ganache 测试环境

// 简化的 artifacts 导出 - 使用编译好的合约
import * as ZrxTreasuryArtifact from '../artifacts/contracts/src/ZrxTreasury.sol/ZrxTreasury.json';
import * as DefaultPoolOperatorArtifact from '../artifacts/contracts/src/DefaultPoolOperator.sol/DefaultPoolOperator.json';

export const artifacts = {
    ZrxTreasury: ZrxTreasuryArtifact as any,
    DefaultPoolOperator: DefaultPoolOperatorArtifact as any,
};

// 如果需要额外的 artifacts，可以在这里导入
// import * as AdditionalContract from './generated-wrappers/additional_contract';

// 兼容性导出 - 保持与原始测试的兼容
export const artifacts_legacy = {
    // 这里可以添加遗留的 artifact 导入
};
