/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
import { ContractArtifact } from 'ethereum-types';

import * as IWallet from '../artifacts/contracts/src/IWallet.sol/IWallet.json';
import * as LibEIP712ExchangeDomain from '../artifacts/contracts/src/LibEIP712ExchangeDomain.sol/LibEIP712ExchangeDomain.json';
import * as LibExchangeRichErrors from '../artifacts/contracts/src/LibExchangeRichErrors.sol/LibExchangeRichErrors.json';
import * as LibFillResults from '../artifacts/contracts/src/LibFillResults.sol/LibFillResults.json';
import * as LibMath from '../artifacts/contracts/src/LibMath.sol/LibMath.json';
import * as LibMathRichErrors from '../artifacts/contracts/src/LibMathRichErrors.sol/LibMathRichErrors.json';
import * as LibOrder from '../artifacts/contracts/src/LibOrder.sol/LibOrder.json';
import * as LibZeroExTransaction from '../artifacts/contracts/src/LibZeroExTransaction.sol/LibZeroExTransaction.json';
export const artifacts = {
    IWallet: IWallet as ContractArtifact,
    LibEIP712ExchangeDomain: LibEIP712ExchangeDomain as ContractArtifact,
    LibExchangeRichErrors: LibExchangeRichErrors as ContractArtifact,
    LibFillResults: LibFillResults as ContractArtifact,
    LibMath: LibMath as ContractArtifact,
    LibMathRichErrors: LibMathRichErrors as ContractArtifact,
    LibOrder: LibOrder as ContractArtifact,
    LibZeroExTransaction: LibZeroExTransaction as ContractArtifact,
};
