/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */

// Import Hardhat artifacts
import * as ERC1155 from '../artifacts/contracts/src/ERC1155.sol/ERC1155.json';
import * as ERC1155Mintable from '../artifacts/contracts/src/ERC1155Mintable.sol/ERC1155Mintable.json';
import * as MixinNonFungibleToken from '../artifacts/contracts/src/MixinNonFungibleToken.sol/MixinNonFungibleToken.json';
import * as IERC1155 from '../artifacts/contracts/src/interfaces/IERC1155.sol/IERC1155.json';
import * as IERC1155Mintable from '../artifacts/contracts/src/interfaces/IERC1155Mintable.sol/IERC1155Mintable.json';
import * as IERC1155Receiver from '../artifacts/contracts/src/interfaces/IERC1155Receiver.sol/IERC1155Receiver.json';

/**
 * ERC1155 包的 Hardhat artifacts
 * 使用 Hardhat 编译生成的 JSON 格式
 */
export const artifacts = {
    ERC1155: ERC1155 as any,
    ERC1155Mintable: ERC1155Mintable as any,
    MixinNonFungibleToken: MixinNonFungibleToken as any,
    IERC1155: IERC1155 as any,
    IERC1155Mintable: IERC1155Mintable as any,
    IERC1155Receiver: IERC1155Receiver as any,
};
