/*
 * This file is auto-generated by @0x/contract-wrappers. Don't edit manually.
 */

// Re-export TypeChain generated types and factories
export {
    ERC1155,
    ERC1155__factory,
    ERC1155Mintable,
    ERC1155Mintable__factory,
    MixinNonFungibleToken,
    MixinNonFungibleToken__factory,
    IERC1155,
    IERC1155__factory,
    IERC1155Mintable,
    IERC1155Mintable__factory,
    IERC1155Receiver,
    IERC1155Receiver__factory,
} from './typechain-types';
