/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
import { ContractArtifact } from 'ethereum-types';

// Main contracts
import * as IStaking from '../artifacts/contracts/src/interfaces/IStaking.sol/IStaking.json';
import * as IStakingEvents from '../artifacts/contracts/src/interfaces/IStakingEvents.sol/IStakingEvents.json';
import * as IStakingProxy from '../artifacts/contracts/src/interfaces/IStakingProxy.sol/IStakingProxy.json';
import * as IZrxVault from '../artifacts/contracts/src/interfaces/IZrxVault.sol/IZrxVault.json';
import * as LibStakingRichErrors from '../artifacts/contracts/src/libs/LibStakingRichErrors.sol/LibStakingRichErrors.json';
import * as Staking from '../artifacts/contracts/src/Staking.sol/Staking.json';
import * as StakingProxy from '../artifacts/contracts/src/StakingProxy.sol/StakingProxy.json';
import * as ZrxVault from '../artifacts/contracts/src/ZrxVault.sol/ZrxVault.json';

export const artifacts = {
    IStaking: IStaking as unknown as ContractArtifact,
    IStakingEvents: IStakingEvents as unknown as ContractArtifact,
    IStakingProxy: IStakingProxy as unknown as ContractArtifact,
    IZrxVault: IZrxVault as unknown as ContractArtifact,
    LibStakingRichErrors: LibStakingRichErrors as unknown as ContractArtifact,
    Staking: Staking as unknown as ContractArtifact,
    StakingProxy: StakingProxy as unknown as ContractArtifact,
    ZrxVault: ZrxVault as unknown as ContractArtifact,
};
