[profile.default]
src = "contracts"
out = "out"
libs = ["../../lib", "node_modules"]
test = "tests"
cache_path = "cache"

solc_version = "0.8.28"
evm_version = "cancun"
optimizer = true
optimizer_runs = 1_000_000
via_ir = false

remappings = [
    "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/",
    "forge-std/=../../lib/forge-std/src/",
]
fs_permissions = [
    { access = "read", path = "./" },
    { access = "read", path = "../" }
]

[profile.default.fuzz]
runs = 256

[profile.ci]
fuzz_runs = 4096

