/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
import { ContractArtifact } from 'ethereum-types';

import * as Authorizable from '../test/generated-artifacts/Authorizable.json';
import * as IAuthorizable from '../test/generated-artifacts/IAuthorizable.json';
import * as IOwnable from '../test/generated-artifacts/IOwnable.json';
import * as LibAuthorizableRichErrors from '../test/generated-artifacts/LibAuthorizableRichErrors.json';
import * as LibBytes from '../test/generated-artifacts/LibBytes.json';
import * as LibBytesRichErrors from '../test/generated-artifacts/LibBytesRichErrors.json';
import * as LibMath from '../test/generated-artifacts/LibMath.json';
import * as LibMathRichErrors from '../test/generated-artifacts/LibMathRichErrors.json';
import * as LibOwnableRichErrors from '../test/generated-artifacts/LibOwnableRichErrors.json';
import * as LibReentrancyGuardRichErrors from '../test/generated-artifacts/LibReentrancyGuardRichErrors.json';
import * as LibRichErrors from '../test/generated-artifacts/LibRichErrors.json';
import * as LibSafeMathRichErrors from '../test/generated-artifacts/LibSafeMathRichErrors.json';
import * as Ownable from '../test/generated-artifacts/Ownable.json';
import * as ReentrancyGuard from '../test/generated-artifacts/ReentrancyGuard.json';

export const artifacts = {
    Authorizable: Authorizable as any,
    IAuthorizable: IAuthorizable as any,
    IOwnable: IOwnable as any,
    LibAuthorizableRichErrors: LibAuthorizableRichErrors as any,
    LibBytes: LibBytes as any,
    LibBytesRichErrors: LibBytesRichErrors as any,
    LibMath: LibMath as any,
    LibMathRichErrors: LibMathRichErrors as any,
    LibOwnableRichErrors: LibOwnableRichErrors as any,
    LibReentrancyGuardRichErrors: LibReentrancyGuardRichErrors as any,
    LibRichErrors: LibRichErrors as any,
    LibSafeMathRichErrors: LibSafeMathRichErrors as any,
    Ownable: Ownable as any,
    ReentrancyGuard: ReentrancyGuard as any,
};
