/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */

// Import Hardhat artifacts
import * as IWallet from '../artifacts/contracts/src/IWallet.sol/IWallet.json';
import * as WalletConstants from '../artifacts/contracts/src/IWallet.sol/WalletConstants.json';
import * as LibEIP712ExchangeDomain from '../artifacts/contracts/src/LibEIP712ExchangeDomain.sol/LibEIP712ExchangeDomain.json';
import * as LibExchangeRichErrors from '../artifacts/contracts/src/LibExchangeRichErrors.sol/LibExchangeRichErrors.json';
import * as LibFillResults from '../artifacts/contracts/src/LibFillResults.sol/LibFillResults.json';
import * as LibMath from '../artifacts/contracts/src/LibMath.sol/LibMath.json';
import * as LibMathRichErrors from '../artifacts/contracts/src/LibMathRichErrors.sol/LibMathRichErrors.json';
import * as LibOrder from '../artifacts/contracts/src/LibOrder.sol/LibOrder.json';
import * as LibZeroExTransaction from '../artifacts/contracts/src/LibZeroExTransaction.sol/LibZeroExTransaction.json';

/**
 * Exchange Libs 包的 Hardhat artifacts
 * 使用 Hardhat 编译生成的 JSON 格式
 */
export const artifacts = {
    IWallet: IWallet as any,
    WalletConstants: WalletConstants as any,
    LibEIP712ExchangeDomain: LibEIP712ExchangeDomain as any,
    LibExchangeRichErrors: LibExchangeRichErrors as any,
    LibFillResults: LibFillResults as any,
    LibMath: LibMath as any,
    LibMathRichErrors: LibMathRichErrors as any,
    LibOrder: LibOrder as any,
    LibZeroExTransaction: LibZeroExTransaction as any,
};
