/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
import { ContractArtifact } from 'ethereum-types';

// TODO: Uncomment these imports once Solidity compilation is successful
// Asset Proxy Core Interfaces
// import * as IAssetData from '../artifacts/contracts/src/interfaces/IAssetData.sol/IAssetData.json';
// import * as IAssetProxy from '../artifacts/contracts/src/interfaces/IAssetProxy.sol/IAssetProxy.json';
// import * as IAssetProxyDispatcher from '../artifacts/contracts/src/interfaces/IAssetProxyDispatcher.sol/IAssetProxyDispatcher.json';
// import * as IAuthorizable from '../artifacts/contracts/src/interfaces/IAuthorizable.sol/IAuthorizable.json';

// Main Asset Proxies
// import * as ERC20Proxy from '../artifacts/contracts/src/ERC20Proxy.sol/ERC20Proxy.json';
// import * as ERC721Proxy from '../artifacts/contracts/src/ERC721Proxy.sol/ERC721Proxy.json';
// import * as ERC1155Proxy from '../artifacts/contracts/src/ERC1155Proxy.sol/ERC1155Proxy.json';
// import * as ERC20BridgeProxy from '../artifacts/contracts/src/ERC20BridgeProxy.sol/ERC20BridgeProxy.json';
// import * as MultiAssetProxy from '../artifacts/contracts/src/MultiAssetProxy.sol/MultiAssetProxy.json';
// import * as StaticCallProxy from '../artifacts/contracts/src/StaticCallProxy.sol/StaticCallProxy.json';

// Bridge Interfaces
// import * as IERC20Bridge from '../artifacts/contracts/src/interfaces/IERC20Bridge.sol/IERC20Bridge.json';

// Placeholder for artifacts - will be populated once contracts compile successfully
export const artifacts: Record<string, ContractArtifact> = {
    // TODO: Add actual artifacts once Solidity compilation is fixed
    // IAssetData: IAssetData as any as ContractArtifact,
    // IAssetProxy: IAssetProxy as any as ContractArtifact,
    // IAssetProxyDispatcher: IAssetProxyDispatcher as any as ContractArtifact,
    // IAuthorizable: IAuthorizable as any as ContractArtifact,
    // IERC20Bridge: IERC20Bridge as any as ContractArtifact,
    // ERC20Proxy: ERC20Proxy as any as ContractArtifact,
    // ERC721Proxy: ERC721Proxy as any as ContractArtifact,
    // ERC1155Proxy: ERC1155Proxy as any as ContractArtifact,
    // ERC20BridgeProxy: ERC20BridgeProxy as any as ContractArtifact,
    // MultiAssetProxy: MultiAssetProxy as any as ContractArtifact,
    // StaticCallProxy: StaticCallProxy as any as ContractArtifact,
};
