/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
// TODO: Uncomment these exports once TypeChain compilation is successful
// Currently all exports are commented out until Solidity compilation issues are resolved

// Asset Proxy Core Interfaces
// export * from '../typechain-types/IAssetData';
// export * from '../typechain-types/IAssetProxy';
// export * from '../typechain-types/IAssetProxyDispatcher';
// export * from '../typechain-types/IAuthorizable';

// Asset Proxy Contracts
// export * from '../typechain-types/ERC20Proxy';
// export * from '../typechain-types/ERC721Proxy';
// export * from '../typechain-types/ERC1155Proxy';
// export * from '../typechain-types/ERC20BridgeProxy';
// export * from '../typechain-types/MultiAssetProxy';
// export * from '../typechain-types/StaticCallProxy';

// Bridge Interfaces
// export * from '../typechain-types/IERC20Bridge';
// export * from '../typechain-types/IBalancerPool';
// export * from '../typechain-types/IBancorNetwork';
// export * from '../typechain-types/IChai';
// export * from '../typechain-types/ICurve';
// export * from '../typechain-types/IDydx';
// export * from '../typechain-types/IDydxBridge';
// export * from '../typechain-types/IEth2Dai';
// export * from '../typechain-types/IGasToken';
// export * from '../typechain-types/IKyberNetworkProxy';
// export * from '../typechain-types/IMStable';
// export * from '../typechain-types/IMooniswap';
// export * from '../typechain-types/IShell';
// export * from '../typechain-types/IUniswapExchange';
// export * from '../typechain-types/IUniswapExchangeFactory';
// export * from '../typechain-types/IUniswapV2Router01';

// Bridge Contracts
// export * from '../typechain-types/BalancerBridge';
// export * from '../typechain-types/BancorBridge';
// export * from '../typechain-types/ChaiBridge';
// export * from '../typechain-types/CreamBridge';
// export * from '../typechain-types/CryptoComBridge';
// export * from '../typechain-types/CurveBridge';
// export * from '../typechain-types/DODOBridge';
// export * from '../typechain-types/DexForwarderBridge';
// export * from '../typechain-types/DydxBridge';
// export * from '../typechain-types/Eth2DaiBridge';
// export * from '../typechain-types/KyberBridge';
// export * from '../typechain-types/MStableBridge';
// export * from '../typechain-types/MooniswapBridge';
// export * from '../typechain-types/ShellBridge';
// export * from '../typechain-types/SnowSwapBridge';
// export * from '../typechain-types/SushiSwapBridge';
// export * from '../typechain-types/SwerveBridge';
// export * from '../typechain-types/UniswapBridge';
// export * from '../typechain-types/UniswapV2Bridge';

// Utility Contracts
// export * from '../typechain-types/MixinGasToken';

// Empty export to make this a valid module
export {};

// Note: Once Solidity compilation is fixed and TypeChain generates the types,
// uncomment the relevant exports above and remove this empty export.
