/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
import type { UtilsFoundryArtifacts, FoundryArtifact } from './foundry-types';

// 导入 Foundry 生成的 JSON artifacts (V08 合约)
import * as AuthorizableV08 from '../out/AuthorizableV08.sol/AuthorizableV08.json';
import * as IAuthorizableV08 from '../out/IAuthorizableV08.sol/IAuthorizableV08.json';
import * as IOwnableV08 from '../out/IOwnableV08.sol/IOwnableV08.json';
import * as LibAuthorizableRichErrorsV08 from '../out/LibAuthorizableRichErrorsV08.sol/LibAuthorizableRichErrorsV08.json';
import * as LibBytesRichErrorsV08 from '../out/LibBytesRichErrorsV08.sol/LibBytesRichErrorsV08.json';
import * as LibBytesV08 from '../out/LibBytesV08.sol/LibBytesV08.json';
import * as LibMathRichErrorsV08 from '../out/LibMathRichErrorsV08.sol/LibMathRichErrorsV08.json';
import * as LibMathV08 from '../out/LibMathV08.sol/LibMathV08.json';
import * as LibOwnableRichErrorsV08 from '../out/LibOwnableRichErrorsV08.sol/LibOwnableRichErrorsV08.json';
import * as LibReentrancyGuardRichErrorsV08 from '../out/LibReentrancyGuardRichErrorsV08.sol/LibReentrancyGuardRichErrorsV08.json';
import * as LibRichErrorsV08 from '../out/LibRichErrorsV08.sol/LibRichErrorsV08.json';
import * as LibSafeMathRichErrorsV08 from '../out/LibSafeMathRichErrorsV08.sol/LibSafeMathRichErrorsV08.json';
import * as OwnableV08 from '../out/OwnableV08.sol/OwnableV08.json';
import * as ReentrancyGuardV08 from '../out/ReentrancyGuardV08.sol/ReentrancyGuardV08.json';

/**
 * Utils 包的 Foundry 原生 artifacts
 * 专注于 V08 版本的合约，直接使用 Foundry JSON 格式
 */
export const artifacts: UtilsFoundryArtifacts = {
    // V08 合约
    AuthorizableV08: AuthorizableV08 as FoundryArtifact,
    IAuthorizableV08: IAuthorizableV08 as FoundryArtifact,
    IOwnableV08: IOwnableV08 as FoundryArtifact,
    LibAuthorizableRichErrorsV08: LibAuthorizableRichErrorsV08 as FoundryArtifact,
    LibBytesRichErrorsV08: LibBytesRichErrorsV08 as FoundryArtifact,
    LibBytesV08: LibBytesV08 as FoundryArtifact,
    LibMathRichErrorsV08: LibMathRichErrorsV08 as FoundryArtifact,
    LibMathV08: LibMathV08 as FoundryArtifact,
    LibOwnableRichErrorsV08: LibOwnableRichErrorsV08 as FoundryArtifact,
    LibReentrancyGuardRichErrorsV08: LibReentrancyGuardRichErrorsV08 as FoundryArtifact,
    LibRichErrorsV08: LibRichErrorsV08 as FoundryArtifact,
    LibSafeMathRichErrorsV08: LibSafeMathRichErrorsV08 as FoundryArtifact,
    OwnableV08: OwnableV08 as FoundryArtifact,
    ReentrancyGuardV08: ReentrancyGuardV08 as FoundryArtifact,
};
