/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
import type { UtilsFoundryArtifacts, FoundryArtifact } from './foundry-types';

// 导入 Foundry 生成的 JSON artifacts（统一版本合约）
import * as Authorizable from '../out/Authorizable.sol/Authorizable.json';
import * as IAuthorizable from '../out/IAuthorizable.sol/IAuthorizable.json';
import * as IOwnable from '../out/IOwnable.sol/IOwnable.json';
import * as LibAuthorizableRichErrors from '../out/LibAuthorizableRichErrors.sol/LibAuthorizableRichErrors.json';
import * as LibBytesRichErrors from '../out/LibBytesRichErrors.sol/LibBytesRichErrors.json';
import * as LibBytes from '../out/LibBytes.sol/LibBytes.json';
import * as LibMathRichErrors from '../out/LibMathRichErrors.sol/LibMathRichErrors.json';
import * as LibMath from '../out/LibMath.sol/LibMath.json';
import * as LibOwnableRichErrors from '../out/LibOwnableRichErrors.sol/LibOwnableRichErrors.json';
import * as LibReentrancyGuardRichErrors from '../out/LibReentrancyGuardRichErrors.sol/LibReentrancyGuardRichErrors.json';
import * as LibRichErrors from '../out/LibRichErrors.sol/LibRichErrors.json';
import * as LibSafeMathRichErrors from '../out/LibSafeMathRichErrors.sol/LibSafeMathRichErrors.json';
import * as Ownable from '../out/Ownable.sol/Ownable.json';
import * as ReentrancyGuard from '../out/ReentrancyGuard.sol/ReentrancyGuard.json';

/**
 * Utils 包的 Foundry 原生 artifacts
 * 使用统一版本的合约，直接使用 Foundry JSON 格式
 */
export const artifacts: UtilsFoundryArtifacts = {
    // 统一版本合约
    Authorizable: Authorizable as FoundryArtifact,
    IAuthorizable: IAuthorizable as FoundryArtifact,
    IOwnable: IOwnable as FoundryArtifact,
    LibAuthorizableRichErrors: LibAuthorizableRichErrors as FoundryArtifact,
    LibBytesRichErrors: LibBytesRichErrors as FoundryArtifact,
    LibBytes: LibBytes as FoundryArtifact,
    LibMathRichErrors: LibMathRichErrors as FoundryArtifact,
    LibMath: LibMath as FoundryArtifact,
    LibOwnableRichErrors: LibOwnableRichErrors as FoundryArtifact,
    LibReentrancyGuardRichErrors: LibReentrancyGuardRichErrors as FoundryArtifact,
    LibRichErrors: LibRichErrors as FoundryArtifact,
    LibSafeMathRichErrors: LibSafeMathRichErrors as FoundryArtifact,
    Ownable: Ownable as FoundryArtifact,
    ReentrancyGuard: ReentrancyGuard as FoundryArtifact,
};
