/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
// TypeChain generated contract types exports
// Note: These will be enabled once TypeChain types are generated
// export * from '../test/typechain-types/Authorizable';
// export * from '../test/typechain-types/IAuthorizable';
// export * from '../test/typechain-types/IOwnable';
// export * from '../test/typechain-types/LibAuthorizableRichErrors';
// export * from '../test/typechain-types/LibBytesRichErrors';
// export * from '../test/typechain-types/LibBytes';
// export * from '../test/typechain-types/LibMathRichErrors';
// export * from '../test/typechain-types/LibMath';
// export * from '../test/typechain-types/LibOwnableRichErrors';
// export * from '../test/typechain-types/LibReentrancyGuardRichErrors';
// export * from '../test/typechain-types/LibRichErrors';
// export * from '../test/typechain-types/LibSafeMathRichErrors';
// export * from '../test/typechain-types/Ownable';
// export * from '../test/typechain-types/ReentrancyGuard';

// Export factory types for contract deployment
// export * from '../test/typechain-types/factories';

// Placeholder export to make this a valid module
export const CONTRACT_WRAPPERS_PLACEHOLDER = 'TypeChain types will be available when contracts are compiled';
