/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
// Export only V08 wrappers that actually exist
export * from '../test/generated-wrappers/authorizable_v08';
export * from '../test/generated-wrappers/i_authorizable_v08';
export * from '../test/generated-wrappers/i_ownable_v08';
export * from '../test/generated-wrappers/lib_authorizable_rich_errors_v08';
export * from '../test/generated-wrappers/lib_bytes_rich_errors_v08';
export * from '../test/generated-wrappers/lib_bytes_v08';
export * from '../test/generated-wrappers/lib_math_rich_errors_v08';
export * from '../test/generated-wrappers/lib_math_v08';
export * from '../test/generated-wrappers/lib_ownable_rich_errors_v08';
export * from '../test/generated-wrappers/lib_reentrancy_guard_rich_errors_v08';
export * from '../test/generated-wrappers/lib_rich_errors_v08';
export * from '../test/generated-wrappers/lib_safe_math_rich_errors_v08';
export * from '../test/generated-wrappers/ownable_v08';
export * from '../test/generated-wrappers/reentrancy_guard_v08';
