/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface TestReentrancyGuardInterface extends Interface {
  getFunction(
    nameOrSignature: "exploitive" | "guarded" | "nonExploitive"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "exploitive",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "guarded", values: [boolean]): string;
  encodeFunctionData(
    functionFragment: "nonExploitive",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "exploitive", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "guarded", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nonExploitive",
    data: BytesLike
  ): Result;
}

export interface TestReentrancyGuard extends BaseContract {
  connect(runner?: ContractRunner | null): TestReentrancyGuard;
  waitForDeployment(): Promise<this>;

  interface: TestReentrancyGuardInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  exploitive: TypedContractMethod<[], [boolean], "nonpayable">;

  guarded: TypedContractMethod<
    [shouldBeAttacked: boolean],
    [boolean],
    "nonpayable"
  >;

  nonExploitive: TypedContractMethod<[], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "exploitive"
  ): TypedContractMethod<[], [boolean], "nonpayable">;
  getFunction(
    nameOrSignature: "guarded"
  ): TypedContractMethod<[shouldBeAttacked: boolean], [boolean], "nonpayable">;
  getFunction(
    nameOrSignature: "nonExploitive"
  ): TypedContractMethod<[], [boolean], "view">;

  filters: {};
}
