/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */

// Import Hardhat artifacts for test contracts
import * as DummyERC721Token from '../artifacts/contracts/test/DummyERC721Token.sol/DummyERC721Token.json';
import * as DummyERC721Receiver from '../artifacts/contracts/test/DummyERC721Receiver.sol/DummyERC721Receiver.json';
import * as InvalidERC721Receiver from '../artifacts/contracts/test/InvalidERC721Receiver.sol/InvalidERC721Receiver.json';

// Import production artifacts
import * as ERC721Token from '../artifacts/contracts/src/ERC721Token.sol/ERC721Token.json';
import * as MintableERC721Token from '../artifacts/contracts/src/MintableERC721Token.sol/MintableERC721Token.json';
import * as IERC721Token from '../artifacts/contracts/src/interfaces/IERC721Token.sol/IERC721Token.json';
import * as IERC721Receiver from '../artifacts/contracts/src/interfaces/IERC721Receiver.sol/IERC721Receiver.json';

// Export artifacts directly as Hardhat format (compatible with ethers.js)
export const artifacts = {
    // Test contracts
    DummyERC721Token: DummyERC721Token,
    DummyERC721Receiver: DummyERC721Receiver,
    InvalidERC721Receiver: InvalidERC721Receiver,

    // Production contracts
    ERC721Token: ERC721Token,
    MintableERC721Token: MintableERC721Token,
    IERC721Token: IERC721Token,
    IERC721Receiver: IERC721Receiver,
};
