/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
import { ContractArtifact } from 'ethereum-types';

// Asset Proxy contracts
import * as ERC1155Proxy from '../artifacts/contracts/src/ERC1155Proxy.sol/ERC1155Proxy.json';
import * as ERC20BridgeProxy from '../artifacts/contracts/src/ERC20BridgeProxy.sol/ERC20BridgeProxy.json';
import * as ERC20Proxy from '../artifacts/contracts/src/ERC20Proxy.sol/ERC20Proxy.json';
import * as ERC721Proxy from '../artifacts/contracts/src/ERC721Proxy.sol/ERC721Proxy.json';
import * as MultiAssetProxy from '../artifacts/contracts/src/MultiAssetProxy.sol/MultiAssetProxy.json';
import * as StaticCallProxy from '../artifacts/contracts/src/StaticCallProxy.sol/StaticCallProxy.json';

// Bridge contracts
import * as BalancerBridge from '../artifacts/contracts/src/bridges/BalancerBridge.sol/BalancerBridge.json';
import * as BancorBridge from '../artifacts/contracts/src/bridges/BancorBridge.sol/BancorBridge.json';
import * as ChaiBridge from '../artifacts/contracts/src/bridges/ChaiBridge.sol/ChaiBridge.json';
import * as CreamBridge from '../artifacts/contracts/src/bridges/CreamBridge.sol/CreamBridge.json';
import * as CryptoComBridge from '../artifacts/contracts/src/bridges/CryptoComBridge.sol/CryptoComBridge.json';
import * as CurveBridge from '../artifacts/contracts/src/bridges/CurveBridge.sol/CurveBridge.json';
import * as DexForwarderBridge from '../artifacts/contracts/src/bridges/DexForwarderBridge.sol/DexForwarderBridge.json';
import * as DODOBridge from '../artifacts/contracts/src/bridges/DODOBridge.sol/DODOBridge.json';
import * as DydxBridge from '../artifacts/contracts/src/bridges/DydxBridge.sol/DydxBridge.json';
import * as Eth2DaiBridge from '../artifacts/contracts/src/bridges/Eth2DaiBridge.sol/Eth2DaiBridge.json';
import * as KyberBridge from '../artifacts/contracts/src/bridges/KyberBridge.sol/KyberBridge.json';
import * as MixinGasToken from '../artifacts/contracts/src/bridges/MixinGasToken.sol/MixinGasToken.json';
import * as MooniswapBridge from '../artifacts/contracts/src/bridges/MooniswapBridge.sol/MooniswapBridge.json';
import * as MStableBridge from '../artifacts/contracts/src/bridges/MStableBridge.sol/MStableBridge.json';
import * as ShellBridge from '../artifacts/contracts/src/bridges/ShellBridge.sol/ShellBridge.json';
import * as SnowSwapBridge from '../artifacts/contracts/src/bridges/SnowSwapBridge.sol/SnowSwapBridge.json';
import * as SushiSwapBridge from '../artifacts/contracts/src/bridges/SushiSwapBridge.sol/SushiSwapBridge.json';
import * as SwerveBridge from '../artifacts/contracts/src/bridges/SwerveBridge.sol/SwerveBridge.json';
import * as UniswapBridge from '../artifacts/contracts/src/bridges/UniswapBridge.sol/UniswapBridge.json';
import * as UniswapV2Bridge from '../artifacts/contracts/src/bridges/UniswapV2Bridge.sol/UniswapV2Bridge.json';

// Interface contracts
import * as IAssetData from '../artifacts/contracts/src/interfaces/IAssetData.sol/IAssetData.json';
import * as IAssetProxy from '../artifacts/contracts/src/interfaces/IAssetProxy.sol/IAssetProxy.json';
import * as IAssetProxyDispatcher from '../artifacts/contracts/src/interfaces/IAssetProxyDispatcher.sol/IAssetProxyDispatcher.json';
import * as IAuthorizable from '../artifacts/contracts/src/interfaces/IAuthorizable.sol/IAuthorizable.json';
import * as IBalancerPool from '../artifacts/contracts/src/interfaces/IBalancerPool.sol/IBalancerPool.json';
import * as IBancorNetwork from '../artifacts/contracts/src/interfaces/IBancorNetwork.sol/IBancorNetwork.json';
import * as IChai from '../artifacts/contracts/src/interfaces/IChai.sol/IChai.json';
import * as ICurve from '../artifacts/contracts/src/interfaces/ICurve.sol/ICurve.json';
import * as IDydx from '../artifacts/contracts/src/interfaces/IDydx.sol/IDydx.json';
import * as IDydxBridge from '../artifacts/contracts/src/interfaces/IDydxBridge.sol/IDydxBridge.json';
import * as IERC20Bridge from '../artifacts/contracts/src/interfaces/IERC20Bridge.sol/IERC20Bridge.json';
import * as IEth2Dai from '../artifacts/contracts/src/interfaces/IEth2Dai.sol/IEth2Dai.json';
import * as IGasToken from '../artifacts/contracts/src/interfaces/IGasToken.sol/IGasToken.json';
import * as IKyberNetworkProxy from '../artifacts/contracts/src/interfaces/IKyberNetworkProxy.sol/IKyberNetworkProxy.json';
import * as IMooniswap from '../artifacts/contracts/src/interfaces/IMooniswap.sol/IMooniswap.json';
import * as IMStable from '../artifacts/contracts/src/interfaces/IMStable.sol/IMStable.json';
import * as IShell from '../artifacts/contracts/src/interfaces/IShell.sol/IShell.json';
import * as IUniswapExchange from '../artifacts/contracts/src/interfaces/IUniswapExchange.sol/IUniswapExchange.json';
import * as IUniswapExchangeFactory from '../artifacts/contracts/src/interfaces/IUniswapExchangeFactory.sol/IUniswapExchangeFactory.json';
import * as IUniswapV2Router01 from '../artifacts/contracts/src/interfaces/IUniswapV2Router01.sol/IUniswapV2Router01.json';

// External dependencies (from @0x packages)
import * as Authorizable from '../artifacts/@0x/contracts-utils/contracts/src/Authorizable.sol/Authorizable.json';
import * as IAuthorizableExternal from '../artifacts/@0x/contracts-utils/contracts/src/interfaces/IAuthorizable.sol/IAuthorizable.json';
import * as Ownable from '../artifacts/@0x/contracts-utils/contracts/src/Ownable.sol/Ownable.json';
import * as LibBytes from '../artifacts/@0x/contracts-utils/contracts/src/LibBytes.sol/LibBytes.json';

// Note: Test contracts are not available in compiled artifacts
// The following would be test contracts if they existed:
// TestBancorBridge, TestChaiBridge, TestDexForwarderBridge, TestDydxBridge,
// TestERC20Bridge, TestEth2DaiBridge, TestKyberBridge, TestStaticCallTarget,
// TestUniswapBridge, TestUniswapV2Bridge

// Also note: MixinAssetProxyDispatcher and MixinAuthorizable are likely internal mixins
// that may not have standalone artifacts
/**
 * Asset-Proxy 包的 Hardhat artifacts
 * 使用 Hardhat 编译生成的标准 artifacts 格式
 */
export const artifacts = {
    // Core Utility contracts
    Authorizable,
    Ownable,
    LibBytes,

    // Asset Proxy contracts
    ERC1155Proxy,
    ERC20BridgeProxy,
    ERC20Proxy,
    ERC721Proxy,
    MultiAssetProxy,
    StaticCallProxy,

    // Bridge contracts
    BalancerBridge,
    BancorBridge,
    ChaiBridge,
    CreamBridge,
    CryptoComBridge,
    CurveBridge,
    DODOBridge,
    DexForwarderBridge,
    DydxBridge,
    Eth2DaiBridge,
    KyberBridge,
    MStableBridge,
    MixinGasToken,
    MooniswapBridge,
    ShellBridge,
    SnowSwapBridge,
    SushiSwapBridge,
    SwerveBridge,
    UniswapBridge,
    UniswapV2Bridge,

    // Interface contracts
    IAssetData,
    IAssetProxy,
    IAssetProxyDispatcher,
    IAuthorizable,
    IBalancerPool,
    IBancorNetwork,
    IChai,
    ICurve,
    IDydx,
    IDydxBridge,
    IERC20Bridge,
    IEth2Dai,
    IGasToken,
    IKyberNetworkProxy,
    IMStable,
    IMooniswap,
    IShell,
    IUniswapExchange,
    IUniswapExchangeFactory,
    IUniswapV2Router01,

    // External interface with different name to avoid conflicts
    IAuthorizableExternal,
};

// 为了向后兼容，也导出单独的 artifacts
export {
    // Core contracts
    Authorizable,
    Ownable,
    LibBytes,

    // Asset Proxy contracts
    ERC1155Proxy,
    ERC20BridgeProxy,
    ERC20Proxy,
    ERC721Proxy,
    MultiAssetProxy,
    StaticCallProxy,

    // Bridge contracts
    BalancerBridge,
    BancorBridge,
    ChaiBridge,
    CreamBridge,
    CryptoComBridge,
    CurveBridge,
    DODOBridge,
    DexForwarderBridge,
    DydxBridge,
    Eth2DaiBridge,
    KyberBridge,
    MStableBridge,
    MixinGasToken,
    MooniswapBridge,
    ShellBridge,
    SnowSwapBridge,
    SushiSwapBridge,
    SwerveBridge,
    UniswapBridge,
    UniswapV2Bridge,

    // Interface contracts
    IAssetData,
    IAssetProxy,
    IAssetProxyDispatcher,
    IAuthorizable,
    IBalancerPool,
    IBancorNetwork,
    IChai,
    ICurve,
    IDydx,
    IDydxBridge,
    IERC20Bridge,
    IEth2Dai,
    IGasToken,
    IKyberNetworkProxy,
    IMStable,
    IMooniswap,
    IShell,
    IUniswapExchange,
    IUniswapExchangeFactory,
    IUniswapV2Router01,
    IAuthorizableExternal,
};
