/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace OrderBook {
  export type OrderStruct = {
    orderId: BigNumberish;
    maker: AddressLike;
    token: AddressLike;
    orderType: BigNumberish;
    price: BigNumberish;
    amount: BigNumberish;
    filledAmount: BigNumberish;
    timestamp: BigNumberish;
    status: BigNumberish;
  };

  export type OrderStructOutput = [
    orderId: bigint,
    maker: string,
    token: string,
    orderType: bigint,
    price: bigint,
    amount: bigint,
    filledAmount: bigint,
    timestamp: bigint,
    status: bigint
  ] & {
    orderId: bigint;
    maker: string;
    token: string;
    orderType: bigint;
    price: bigint;
    amount: bigint;
    filledAmount: bigint;
    timestamp: bigint;
    status: bigint;
  };
}

export interface OrderBookInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "buyOrderIds"
      | "calculateFillCost"
      | "cancelOrder"
      | "createBuyOrder"
      | "createSellOrder"
      | "fillOrder"
      | "getActiveBuyOrders"
      | "getActiveSellOrders"
      | "getOrder"
      | "getRemainingAmount"
      | "getUserOrders"
      | "orderCounter"
      | "orders"
      | "sellOrderIds"
      | "userOrders"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OrderCancelled"
      | "OrderCreated"
      | "OrderFilled"
      | "OrderFullyFilled"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "buyOrderIds",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateFillCost",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelOrder",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createBuyOrder",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createSellOrder",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fillOrder",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveBuyOrders",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveSellOrders",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getOrder",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRemainingAmount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserOrders",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "orderCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "orders",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "sellOrderIds",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userOrders",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "buyOrderIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateFillCost",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createBuyOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createSellOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fillOrder", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getActiveBuyOrders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveSellOrders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getOrder", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRemainingAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserOrders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "orderCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "orders", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sellOrderIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "userOrders", data: BytesLike): Result;
}

export namespace OrderCancelledEvent {
  export type InputTuple = [
    orderId: BigNumberish,
    maker: AddressLike,
    refundedAmount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    orderId: bigint,
    maker: string,
    refundedAmount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    orderId: bigint;
    maker: string;
    refundedAmount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderCreatedEvent {
  export type InputTuple = [
    orderId: BigNumberish,
    maker: AddressLike,
    token: AddressLike,
    orderType: BigNumberish,
    price: BigNumberish,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    orderId: bigint,
    maker: string,
    token: string,
    orderType: bigint,
    price: bigint,
    amount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    orderId: bigint;
    maker: string;
    token: string;
    orderType: bigint;
    price: bigint;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderFilledEvent {
  export type InputTuple = [
    orderId: BigNumberish,
    taker: AddressLike,
    fillAmount: BigNumberish,
    remainingAmount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    orderId: bigint,
    taker: string,
    fillAmount: bigint,
    remainingAmount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    orderId: bigint;
    taker: string;
    fillAmount: bigint;
    remainingAmount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderFullyFilledEvent {
  export type InputTuple = [orderId: BigNumberish, timestamp: BigNumberish];
  export type OutputTuple = [orderId: bigint, timestamp: bigint];
  export interface OutputObject {
    orderId: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface OrderBook extends BaseContract {
  connect(runner?: ContractRunner | null): OrderBook;
  waitForDeployment(): Promise<this>;

  interface: OrderBookInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  buyOrderIds: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  calculateFillCost: TypedContractMethod<
    [orderId: BigNumberish, fillAmount: BigNumberish],
    [bigint],
    "view"
  >;

  cancelOrder: TypedContractMethod<
    [orderId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createBuyOrder: TypedContractMethod<
    [token: AddressLike, price: BigNumberish, amount: BigNumberish],
    [bigint],
    "payable"
  >;

  createSellOrder: TypedContractMethod<
    [token: AddressLike, price: BigNumberish, amount: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  fillOrder: TypedContractMethod<
    [orderId: BigNumberish, fillAmount: BigNumberish],
    [bigint],
    "payable"
  >;

  getActiveBuyOrders: TypedContractMethod<
    [token: AddressLike, offset: BigNumberish, limit: BigNumberish],
    [OrderBook.OrderStructOutput[]],
    "view"
  >;

  getActiveSellOrders: TypedContractMethod<
    [token: AddressLike, offset: BigNumberish, limit: BigNumberish],
    [OrderBook.OrderStructOutput[]],
    "view"
  >;

  getOrder: TypedContractMethod<
    [orderId: BigNumberish],
    [OrderBook.OrderStructOutput],
    "view"
  >;

  getRemainingAmount: TypedContractMethod<
    [orderId: BigNumberish],
    [bigint],
    "view"
  >;

  getUserOrders: TypedContractMethod<[user: AddressLike], [bigint[]], "view">;

  orderCounter: TypedContractMethod<[], [bigint], "view">;

  orders: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        orderId: bigint;
        maker: string;
        token: string;
        orderType: bigint;
        price: bigint;
        amount: bigint;
        filledAmount: bigint;
        timestamp: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  sellOrderIds: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  userOrders: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "buyOrderIds"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "calculateFillCost"
  ): TypedContractMethod<
    [orderId: BigNumberish, fillAmount: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "cancelOrder"
  ): TypedContractMethod<[orderId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createBuyOrder"
  ): TypedContractMethod<
    [token: AddressLike, price: BigNumberish, amount: BigNumberish],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "createSellOrder"
  ): TypedContractMethod<
    [token: AddressLike, price: BigNumberish, amount: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fillOrder"
  ): TypedContractMethod<
    [orderId: BigNumberish, fillAmount: BigNumberish],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "getActiveBuyOrders"
  ): TypedContractMethod<
    [token: AddressLike, offset: BigNumberish, limit: BigNumberish],
    [OrderBook.OrderStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getActiveSellOrders"
  ): TypedContractMethod<
    [token: AddressLike, offset: BigNumberish, limit: BigNumberish],
    [OrderBook.OrderStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOrder"
  ): TypedContractMethod<
    [orderId: BigNumberish],
    [OrderBook.OrderStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRemainingAmount"
  ): TypedContractMethod<[orderId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserOrders"
  ): TypedContractMethod<[user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "orderCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "orders"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        orderId: bigint;
        maker: string;
        token: string;
        orderType: bigint;
        price: bigint;
        amount: bigint;
        filledAmount: bigint;
        timestamp: bigint;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "sellOrderIds"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "userOrders"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getEvent(
    key: "OrderCancelled"
  ): TypedContractEvent<
    OrderCancelledEvent.InputTuple,
    OrderCancelledEvent.OutputTuple,
    OrderCancelledEvent.OutputObject
  >;
  getEvent(
    key: "OrderCreated"
  ): TypedContractEvent<
    OrderCreatedEvent.InputTuple,
    OrderCreatedEvent.OutputTuple,
    OrderCreatedEvent.OutputObject
  >;
  getEvent(
    key: "OrderFilled"
  ): TypedContractEvent<
    OrderFilledEvent.InputTuple,
    OrderFilledEvent.OutputTuple,
    OrderFilledEvent.OutputObject
  >;
  getEvent(
    key: "OrderFullyFilled"
  ): TypedContractEvent<
    OrderFullyFilledEvent.InputTuple,
    OrderFullyFilledEvent.OutputTuple,
    OrderFullyFilledEvent.OutputObject
  >;

  filters: {
    "OrderCancelled(uint256,address,uint256,uint256)": TypedContractEvent<
      OrderCancelledEvent.InputTuple,
      OrderCancelledEvent.OutputTuple,
      OrderCancelledEvent.OutputObject
    >;
    OrderCancelled: TypedContractEvent<
      OrderCancelledEvent.InputTuple,
      OrderCancelledEvent.OutputTuple,
      OrderCancelledEvent.OutputObject
    >;

    "OrderCreated(uint256,address,address,uint8,uint256,uint256,uint256)": TypedContractEvent<
      OrderCreatedEvent.InputTuple,
      OrderCreatedEvent.OutputTuple,
      OrderCreatedEvent.OutputObject
    >;
    OrderCreated: TypedContractEvent<
      OrderCreatedEvent.InputTuple,
      OrderCreatedEvent.OutputTuple,
      OrderCreatedEvent.OutputObject
    >;

    "OrderFilled(uint256,address,uint256,uint256,uint256)": TypedContractEvent<
      OrderFilledEvent.InputTuple,
      OrderFilledEvent.OutputTuple,
      OrderFilledEvent.OutputObject
    >;
    OrderFilled: TypedContractEvent<
      OrderFilledEvent.InputTuple,
      OrderFilledEvent.OutputTuple,
      OrderFilledEvent.OutputObject
    >;

    "OrderFullyFilled(uint256,uint256)": TypedContractEvent<
      OrderFullyFilledEvent.InputTuple,
      OrderFullyFilledEvent.OutputTuple,
      OrderFullyFilledEvent.OutputObject
    >;
    OrderFullyFilled: TypedContractEvent<
      OrderFullyFilledEvent.InputTuple,
      OrderFullyFilledEvent.OutputTuple,
      OrderFullyFilledEvent.OutputObject
    >;
  };
}
