/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */

// Import Hardhat artifacts for test contracts
import * as DummyERC20Token from '../artifacts/contracts/test/DummyERC20Token.sol/DummyERC20Token.json';
import * as DummyMultipleReturnERC20Token from '../artifacts/contracts/test/DummyMultipleReturnERC20Token.sol/DummyMultipleReturnERC20Token.json';
import * as DummyNoReturnERC20Token from '../artifacts/contracts/test/DummyNoReturnERC20Token.sol/DummyNoReturnERC20Token.json';
import * as TestLibERC20Token from '../artifacts/contracts/test/TestLibERC20Token.sol/TestLibERC20Token.json';
import * as TestLibERC20TokenTarget from '../artifacts/contracts/test/TestLibERC20TokenTarget.sol/TestLibERC20TokenTarget.json';
import * as UntransferrableDummyERC20Token from '../artifacts/contracts/test/UntransferrableDummyERC20Token.sol/UntransferrableDummyERC20Token.json';

// Import production artifacts
import * as ERC20Token from '../artifacts/contracts/src/ERC20Token.sol/ERC20Token.json';
import * as LibERC20Token from '../artifacts/contracts/src/LibERC20Token.sol/LibERC20Token.json';
import * as MintableERC20Token from '../artifacts/contracts/src/MintableERC20Token.sol/MintableERC20Token.json';
import * as UnlimitedAllowanceERC20Token from '../artifacts/contracts/src/UnlimitedAllowanceERC20Token.sol/UnlimitedAllowanceERC20Token.json';
import * as WETH9 from '../artifacts/contracts/src/WETH9.sol/WETH9.json';
import * as IERC20Token from '../artifacts/contracts/src/interfaces/IERC20Token.sol/IERC20Token.json';
import * as IEtherToken from '../artifacts/contracts/src/interfaces/IEtherToken.sol/IEtherToken.json';

// Export artifacts directly as Hardhat format (compatible with ethers.js)
export const artifacts = {
    // Test contracts
    DummyERC20Token: DummyERC20Token,
    DummyMultipleReturnERC20Token: DummyMultipleReturnERC20Token,
    DummyNoReturnERC20Token: DummyNoReturnERC20Token,
    TestLibERC20Token: TestLibERC20Token,
    TestLibERC20TokenTarget: TestLibERC20TokenTarget,
    UntransferrableDummyERC20Token: UntransferrableDummyERC20Token,

    // Production contracts
    ERC20Token: ERC20Token,
    LibERC20Token: LibERC20Token,
    MintableERC20Token: MintableERC20Token,
    UnlimitedAllowanceERC20Token: UnlimitedAllowanceERC20Token,
    WETH9: WETH9,
    IERC20Token: IERC20Token,
    IEtherToken: IEtherToken,
};
