/*
 * This file is auto-generated by @0x/contract-wrappers. Don't edit manually.
 */

// Re-export TypeChain generated types and factories for testing
export {
    // Test contracts
    DummyERC20Token,
    DummyERC20Token__factory,
    DummyMultipleReturnERC20Token,
    DummyMultipleReturnERC20Token__factory,
    DummyNoReturnERC20Token,
    DummyNoReturnERC20Token__factory,
    TestLibERC20Token,
    TestLibERC20Token__factory,
    TestLibERC20TokenTarget,
    TestLibERC20TokenTarget__factory,
    UntransferrableDummyERC20Token,
    UntransferrableDummyERC20Token__factory,

    // Production contracts for testing
    ERC20Token,
    ERC20Token__factory,
    MintableERC20Token,
    MintableERC20Token__factory,
    UnlimitedAllowanceERC20Token,
    UnlimitedAllowanceERC20Token__factory,
    WETH9,
    WETH9__factory,
    IERC20Token,
    IERC20Token__factory,
    IEtherToken,
    IEtherToken__factory,
} from '../typechain-types';
