/*
 * This file is auto-generated by @0x/contract-wrappers. Don't edit manually.
 */

// Re-export TypeChain generated types and factories for testing
export {
    // Test contracts
    DummyERC20Token,
    DummyERC20Token__factory,
    DummyMultipleReturnERC20Token,
    DummyMultipleReturnERC20Token__factory,
    DummyNoReturnERC20Token,
    DummyNoReturnERC20Token__factory,
    TestLibERC20Token,
    TestLibERC20Token__factory,
    TestLibERC20TokenTarget,
    TestLibERC20TokenTarget__factory,
    UntransferrableDummyERC20Token,
    UntransferrableDummyERC20Token__factory,

    // Production contracts for testing
    ERC20Token,
    ERC20Token__factory,
    MintableERC20Token,
    MintableERC20Token__factory,
    UnlimitedAllowanceERC20Token,
    UnlimitedAllowanceERC20Token__factory,
    WETH9,
    WETH9__factory,
    ZRXToken,
    ZRXToken__factory,
    IERC20Token,
    IERC20Token__factory,
    IEtherToken,
    IEtherToken__factory,
} from '../src/typechain-types';

// Re-export event namespaces for testing
export {
    ApproveCalledEvent,
    TransferCalledEvent,
    TransferFromCalledEvent,
} from '../src/typechain-types/contracts/test/TestLibERC20TokenTarget';

// Legacy compatibility: Create event objects for old test patterns
export const TestLibERC20TokenTargetEvents = {
    ApproveCalled: 'ApproveCalled' as const,
    TransferCalled: 'TransferCalled' as const,
    TransferFromCalled: 'TransferFromCalled' as const,
};
