/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface CurveLiquidityProviderInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getSellQuote"
      | "sellEthForToken"
      | "sellTokenForEth"
      | "sellTokenForToken"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "LiquidityProviderFill"): EventFragment;

  encodeFunctionData(
    functionFragment: "getSellQuote",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "sellEthForToken",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sellTokenForEth",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sellTokenForToken",
    values: [AddressLike, AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getSellQuote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sellEthForToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sellTokenForEth",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sellTokenForToken",
    data: BytesLike
  ): Result;
}

export namespace LiquidityProviderFillEvent {
  export type InputTuple = [
    inputToken: AddressLike,
    outputToken: AddressLike,
    inputTokenAmount: BigNumberish,
    outputTokenAmount: BigNumberish,
    sourceId: BytesLike,
    sourceAddress: AddressLike,
    sender: AddressLike,
    recipient: AddressLike
  ];
  export type OutputTuple = [
    inputToken: string,
    outputToken: string,
    inputTokenAmount: bigint,
    outputTokenAmount: bigint,
    sourceId: string,
    sourceAddress: string,
    sender: string,
    recipient: string
  ];
  export interface OutputObject {
    inputToken: string;
    outputToken: string;
    inputTokenAmount: bigint;
    outputTokenAmount: bigint;
    sourceId: string;
    sourceAddress: string;
    sender: string;
    recipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CurveLiquidityProvider extends BaseContract {
  connect(runner?: ContractRunner | null): CurveLiquidityProvider;
  waitForDeployment(): Promise<this>;

  interface: CurveLiquidityProviderInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getSellQuote: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish],
    [bigint],
    "view"
  >;

  sellEthForToken: TypedContractMethod<
    [
      outputToken: AddressLike,
      recipient: AddressLike,
      minBuyAmount: BigNumberish,
      auxiliaryData: BytesLike
    ],
    [bigint],
    "payable"
  >;

  sellTokenForEth: TypedContractMethod<
    [
      inputToken: AddressLike,
      recipient: AddressLike,
      minBuyAmount: BigNumberish,
      auxiliaryData: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  sellTokenForToken: TypedContractMethod<
    [
      inputToken: AddressLike,
      outputToken: AddressLike,
      recipient: AddressLike,
      minBuyAmount: BigNumberish,
      auxiliaryData: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getSellQuote"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "sellEthForToken"
  ): TypedContractMethod<
    [
      outputToken: AddressLike,
      recipient: AddressLike,
      minBuyAmount: BigNumberish,
      auxiliaryData: BytesLike
    ],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "sellTokenForEth"
  ): TypedContractMethod<
    [
      inputToken: AddressLike,
      recipient: AddressLike,
      minBuyAmount: BigNumberish,
      auxiliaryData: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sellTokenForToken"
  ): TypedContractMethod<
    [
      inputToken: AddressLike,
      outputToken: AddressLike,
      recipient: AddressLike,
      minBuyAmount: BigNumberish,
      auxiliaryData: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  getEvent(
    key: "LiquidityProviderFill"
  ): TypedContractEvent<
    LiquidityProviderFillEvent.InputTuple,
    LiquidityProviderFillEvent.OutputTuple,
    LiquidityProviderFillEvent.OutputObject
  >;

  filters: {
    "LiquidityProviderFill(address,address,uint256,uint256,bytes32,address,address,address)": TypedContractEvent<
      LiquidityProviderFillEvent.InputTuple,
      LiquidityProviderFillEvent.OutputTuple,
      LiquidityProviderFillEvent.OutputObject
    >;
    LiquidityProviderFill: TypedContractEvent<
      LiquidityProviderFillEvent.InputTuple,
      LiquidityProviderFillEvent.OutputTuple,
      LiquidityProviderFillEvent.OutputObject
    >;
  };
}
