/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace IERC20Transformer {
  export type TransformContextStruct = {
    sender: AddressLike;
    recipient: AddressLike;
    data: BytesLike;
  };

  export type TransformContextStructOutput = [
    sender: string,
    recipient: string,
    data: string
  ] & { sender: string; recipient: string; data: string };
}

export interface FillQuoteTransformerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "bridgeAdapter"
      | "deployer"
      | "die"
      | "transform"
      | "zeroEx"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "ProtocolFeeUnfunded"): EventFragment;

  encodeFunctionData(
    functionFragment: "bridgeAdapter",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "deployer", values?: undefined): string;
  encodeFunctionData(functionFragment: "die", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "transform",
    values: [IERC20Transformer.TransformContextStruct]
  ): string;
  encodeFunctionData(functionFragment: "zeroEx", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "bridgeAdapter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deployer", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "die", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "transform", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "zeroEx", data: BytesLike): Result;
}

export namespace ProtocolFeeUnfundedEvent {
  export type InputTuple = [orderHash: BytesLike];
  export type OutputTuple = [orderHash: string];
  export interface OutputObject {
    orderHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FillQuoteTransformer extends BaseContract {
  connect(runner?: ContractRunner | null): FillQuoteTransformer;
  waitForDeployment(): Promise<this>;

  interface: FillQuoteTransformerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  bridgeAdapter: TypedContractMethod<[], [string], "view">;

  deployer: TypedContractMethod<[], [string], "view">;

  die: TypedContractMethod<[ethRecipient: AddressLike], [void], "nonpayable">;

  transform: TypedContractMethod<
    [context: IERC20Transformer.TransformContextStruct],
    [string],
    "nonpayable"
  >;

  zeroEx: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "bridgeAdapter"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "deployer"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "die"
  ): TypedContractMethod<[ethRecipient: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transform"
  ): TypedContractMethod<
    [context: IERC20Transformer.TransformContextStruct],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "zeroEx"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "ProtocolFeeUnfunded"
  ): TypedContractEvent<
    ProtocolFeeUnfundedEvent.InputTuple,
    ProtocolFeeUnfundedEvent.OutputTuple,
    ProtocolFeeUnfundedEvent.OutputObject
  >;

  filters: {
    "ProtocolFeeUnfunded(bytes32)": TypedContractEvent<
      ProtocolFeeUnfundedEvent.InputTuple,
      ProtocolFeeUnfundedEvent.OutputTuple,
      ProtocolFeeUnfundedEvent.OutputObject
    >;
    ProtocolFeeUnfunded: TypedContractEvent<
      ProtocolFeeUnfundedEvent.InputTuple,
      ProtocolFeeUnfundedEvent.OutputTuple,
      ProtocolFeeUnfundedEvent.OutputObject
    >;
  };
}
