/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace IMultiplexFeature {
  export type BatchSellSubcallStruct = {
    id: BigNumberish;
    sellAmount: BigNumberish;
    data: BytesLike;
  };

  export type BatchSellSubcallStructOutput = [
    id: bigint,
    sellAmount: bigint,
    data: string
  ] & { id: bigint; sellAmount: bigint; data: string };

  export type BatchSellParamsStruct = {
    inputToken: AddressLike;
    outputToken: AddressLike;
    sellAmount: BigNumberish;
    calls: IMultiplexFeature.BatchSellSubcallStruct[];
    useSelfBalance: boolean;
    recipient: AddressLike;
    payer: AddressLike;
  };

  export type BatchSellParamsStructOutput = [
    inputToken: string,
    outputToken: string,
    sellAmount: bigint,
    calls: IMultiplexFeature.BatchSellSubcallStructOutput[],
    useSelfBalance: boolean,
    recipient: string,
    payer: string
  ] & {
    inputToken: string;
    outputToken: string;
    sellAmount: bigint;
    calls: IMultiplexFeature.BatchSellSubcallStructOutput[];
    useSelfBalance: boolean;
    recipient: string;
    payer: string;
  };

  export type MultiHopSellSubcallStruct = { id: BigNumberish; data: BytesLike };

  export type MultiHopSellSubcallStructOutput = [id: bigint, data: string] & {
    id: bigint;
    data: string;
  };

  export type MultiHopSellParamsStruct = {
    tokens: AddressLike[];
    sellAmount: BigNumberish;
    calls: IMultiplexFeature.MultiHopSellSubcallStruct[];
    useSelfBalance: boolean;
    recipient: AddressLike;
    payer: AddressLike;
  };

  export type MultiHopSellParamsStructOutput = [
    tokens: string[],
    sellAmount: bigint,
    calls: IMultiplexFeature.MultiHopSellSubcallStructOutput[],
    useSelfBalance: boolean,
    recipient: string,
    payer: string
  ] & {
    tokens: string[];
    sellAmount: bigint;
    calls: IMultiplexFeature.MultiHopSellSubcallStructOutput[];
    useSelfBalance: boolean;
    recipient: string;
    payer: string;
  };
}

export interface MultiplexFeatureInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "EIP712_DOMAIN_SEPARATOR"
      | "FEATURE_NAME"
      | "FEATURE_VERSION"
      | "_batchSellLiquidityProviderExternal"
      | "_batchSellUniswapV2External"
      | "_multiplexBatchSell"
      | "_multiplexMultiHopSell"
      | "migrate"
      | "multiplexBatchSellEthForToken"
      | "multiplexBatchSellTokenForEth"
      | "multiplexBatchSellTokenForToken"
      | "multiplexMultiHopSellEthForToken"
      | "multiplexMultiHopSellTokenForEth"
      | "multiplexMultiHopSellTokenForToken"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ExpiredOtcOrder"
      | "ExpiredRfqOrder"
      | "LiquidityProviderSwap"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "EIP712_DOMAIN_SEPARATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "FEATURE_NAME",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "FEATURE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "_batchSellLiquidityProviderExternal",
    values: [IMultiplexFeature.BatchSellParamsStruct, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "_batchSellUniswapV2External",
    values: [IMultiplexFeature.BatchSellParamsStruct, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "_multiplexBatchSell",
    values: [IMultiplexFeature.BatchSellParamsStruct, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "_multiplexMultiHopSell",
    values: [IMultiplexFeature.MultiHopSellParamsStruct, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "migrate", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "multiplexBatchSellEthForToken",
    values: [
      AddressLike,
      IMultiplexFeature.BatchSellSubcallStruct[],
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "multiplexBatchSellTokenForEth",
    values: [
      AddressLike,
      IMultiplexFeature.BatchSellSubcallStruct[],
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "multiplexBatchSellTokenForToken",
    values: [
      AddressLike,
      AddressLike,
      IMultiplexFeature.BatchSellSubcallStruct[],
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "multiplexMultiHopSellEthForToken",
    values: [
      AddressLike[],
      IMultiplexFeature.MultiHopSellSubcallStruct[],
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "multiplexMultiHopSellTokenForEth",
    values: [
      AddressLike[],
      IMultiplexFeature.MultiHopSellSubcallStruct[],
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "multiplexMultiHopSellTokenForToken",
    values: [
      AddressLike[],
      IMultiplexFeature.MultiHopSellSubcallStruct[],
      BigNumberish,
      BigNumberish
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "EIP712_DOMAIN_SEPARATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FEATURE_NAME",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FEATURE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_batchSellLiquidityProviderExternal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_batchSellUniswapV2External",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_multiplexBatchSell",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_multiplexMultiHopSell",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "migrate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "multiplexBatchSellEthForToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "multiplexBatchSellTokenForEth",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "multiplexBatchSellTokenForToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "multiplexMultiHopSellEthForToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "multiplexMultiHopSellTokenForEth",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "multiplexMultiHopSellTokenForToken",
    data: BytesLike
  ): Result;
}

export namespace ExpiredOtcOrderEvent {
  export type InputTuple = [
    orderHash: BytesLike,
    maker: AddressLike,
    expiry: BigNumberish
  ];
  export type OutputTuple = [orderHash: string, maker: string, expiry: bigint];
  export interface OutputObject {
    orderHash: string;
    maker: string;
    expiry: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExpiredRfqOrderEvent {
  export type InputTuple = [
    orderHash: BytesLike,
    maker: AddressLike,
    expiry: BigNumberish
  ];
  export type OutputTuple = [orderHash: string, maker: string, expiry: bigint];
  export interface OutputObject {
    orderHash: string;
    maker: string;
    expiry: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidityProviderSwapEvent {
  export type InputTuple = [
    inputToken: AddressLike,
    outputToken: AddressLike,
    inputTokenAmount: BigNumberish,
    outputTokenAmount: BigNumberish,
    provider: AddressLike,
    recipient: AddressLike
  ];
  export type OutputTuple = [
    inputToken: string,
    outputToken: string,
    inputTokenAmount: bigint,
    outputTokenAmount: bigint,
    provider: string,
    recipient: string
  ];
  export interface OutputObject {
    inputToken: string;
    outputToken: string;
    inputTokenAmount: bigint;
    outputTokenAmount: bigint;
    provider: string;
    recipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MultiplexFeature extends BaseContract {
  connect(runner?: ContractRunner | null): MultiplexFeature;
  waitForDeployment(): Promise<this>;

  interface: MultiplexFeatureInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  EIP712_DOMAIN_SEPARATOR: TypedContractMethod<[], [string], "view">;

  FEATURE_NAME: TypedContractMethod<[], [string], "view">;

  FEATURE_VERSION: TypedContractMethod<[], [bigint], "view">;

  _batchSellLiquidityProviderExternal: TypedContractMethod<
    [
      params: IMultiplexFeature.BatchSellParamsStruct,
      wrappedCallData: BytesLike,
      sellAmount: BigNumberish
    ],
    [bigint],
    "payable"
  >;

  _batchSellUniswapV2External: TypedContractMethod<
    [
      params: IMultiplexFeature.BatchSellParamsStruct,
      wrappedCallData: BytesLike,
      sellAmount: BigNumberish
    ],
    [bigint],
    "payable"
  >;

  _multiplexBatchSell: TypedContractMethod<
    [
      params: IMultiplexFeature.BatchSellParamsStruct,
      minBuyAmount: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  _multiplexMultiHopSell: TypedContractMethod<
    [
      params: IMultiplexFeature.MultiHopSellParamsStruct,
      minBuyAmount: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  migrate: TypedContractMethod<[], [string], "nonpayable">;

  multiplexBatchSellEthForToken: TypedContractMethod<
    [
      outputToken: AddressLike,
      calls: IMultiplexFeature.BatchSellSubcallStruct[],
      minBuyAmount: BigNumberish
    ],
    [bigint],
    "payable"
  >;

  multiplexBatchSellTokenForEth: TypedContractMethod<
    [
      inputToken: AddressLike,
      calls: IMultiplexFeature.BatchSellSubcallStruct[],
      sellAmount: BigNumberish,
      minBuyAmount: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  multiplexBatchSellTokenForToken: TypedContractMethod<
    [
      inputToken: AddressLike,
      outputToken: AddressLike,
      calls: IMultiplexFeature.BatchSellSubcallStruct[],
      sellAmount: BigNumberish,
      minBuyAmount: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  multiplexMultiHopSellEthForToken: TypedContractMethod<
    [
      tokens: AddressLike[],
      calls: IMultiplexFeature.MultiHopSellSubcallStruct[],
      minBuyAmount: BigNumberish
    ],
    [bigint],
    "payable"
  >;

  multiplexMultiHopSellTokenForEth: TypedContractMethod<
    [
      tokens: AddressLike[],
      calls: IMultiplexFeature.MultiHopSellSubcallStruct[],
      sellAmount: BigNumberish,
      minBuyAmount: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  multiplexMultiHopSellTokenForToken: TypedContractMethod<
    [
      tokens: AddressLike[],
      calls: IMultiplexFeature.MultiHopSellSubcallStruct[],
      sellAmount: BigNumberish,
      minBuyAmount: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "EIP712_DOMAIN_SEPARATOR"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "FEATURE_NAME"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "FEATURE_VERSION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "_batchSellLiquidityProviderExternal"
  ): TypedContractMethod<
    [
      params: IMultiplexFeature.BatchSellParamsStruct,
      wrappedCallData: BytesLike,
      sellAmount: BigNumberish
    ],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "_batchSellUniswapV2External"
  ): TypedContractMethod<
    [
      params: IMultiplexFeature.BatchSellParamsStruct,
      wrappedCallData: BytesLike,
      sellAmount: BigNumberish
    ],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "_multiplexBatchSell"
  ): TypedContractMethod<
    [
      params: IMultiplexFeature.BatchSellParamsStruct,
      minBuyAmount: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "_multiplexMultiHopSell"
  ): TypedContractMethod<
    [
      params: IMultiplexFeature.MultiHopSellParamsStruct,
      minBuyAmount: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "migrate"
  ): TypedContractMethod<[], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "multiplexBatchSellEthForToken"
  ): TypedContractMethod<
    [
      outputToken: AddressLike,
      calls: IMultiplexFeature.BatchSellSubcallStruct[],
      minBuyAmount: BigNumberish
    ],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "multiplexBatchSellTokenForEth"
  ): TypedContractMethod<
    [
      inputToken: AddressLike,
      calls: IMultiplexFeature.BatchSellSubcallStruct[],
      sellAmount: BigNumberish,
      minBuyAmount: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "multiplexBatchSellTokenForToken"
  ): TypedContractMethod<
    [
      inputToken: AddressLike,
      outputToken: AddressLike,
      calls: IMultiplexFeature.BatchSellSubcallStruct[],
      sellAmount: BigNumberish,
      minBuyAmount: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "multiplexMultiHopSellEthForToken"
  ): TypedContractMethod<
    [
      tokens: AddressLike[],
      calls: IMultiplexFeature.MultiHopSellSubcallStruct[],
      minBuyAmount: BigNumberish
    ],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "multiplexMultiHopSellTokenForEth"
  ): TypedContractMethod<
    [
      tokens: AddressLike[],
      calls: IMultiplexFeature.MultiHopSellSubcallStruct[],
      sellAmount: BigNumberish,
      minBuyAmount: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "multiplexMultiHopSellTokenForToken"
  ): TypedContractMethod<
    [
      tokens: AddressLike[],
      calls: IMultiplexFeature.MultiHopSellSubcallStruct[],
      sellAmount: BigNumberish,
      minBuyAmount: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  getEvent(
    key: "ExpiredOtcOrder"
  ): TypedContractEvent<
    ExpiredOtcOrderEvent.InputTuple,
    ExpiredOtcOrderEvent.OutputTuple,
    ExpiredOtcOrderEvent.OutputObject
  >;
  getEvent(
    key: "ExpiredRfqOrder"
  ): TypedContractEvent<
    ExpiredRfqOrderEvent.InputTuple,
    ExpiredRfqOrderEvent.OutputTuple,
    ExpiredRfqOrderEvent.OutputObject
  >;
  getEvent(
    key: "LiquidityProviderSwap"
  ): TypedContractEvent<
    LiquidityProviderSwapEvent.InputTuple,
    LiquidityProviderSwapEvent.OutputTuple,
    LiquidityProviderSwapEvent.OutputObject
  >;

  filters: {
    "ExpiredOtcOrder(bytes32,address,uint64)": TypedContractEvent<
      ExpiredOtcOrderEvent.InputTuple,
      ExpiredOtcOrderEvent.OutputTuple,
      ExpiredOtcOrderEvent.OutputObject
    >;
    ExpiredOtcOrder: TypedContractEvent<
      ExpiredOtcOrderEvent.InputTuple,
      ExpiredOtcOrderEvent.OutputTuple,
      ExpiredOtcOrderEvent.OutputObject
    >;

    "ExpiredRfqOrder(bytes32,address,uint64)": TypedContractEvent<
      ExpiredRfqOrderEvent.InputTuple,
      ExpiredRfqOrderEvent.OutputTuple,
      ExpiredRfqOrderEvent.OutputObject
    >;
    ExpiredRfqOrder: TypedContractEvent<
      ExpiredRfqOrderEvent.InputTuple,
      ExpiredRfqOrderEvent.OutputTuple,
      ExpiredRfqOrderEvent.OutputObject
    >;

    "LiquidityProviderSwap(address,address,uint256,uint256,address,address)": TypedContractEvent<
      LiquidityProviderSwapEvent.InputTuple,
      LiquidityProviderSwapEvent.OutputTuple,
      LiquidityProviderSwapEvent.OutputObject
    >;
    LiquidityProviderSwap: TypedContractEvent<
      LiquidityProviderSwapEvent.InputTuple,
      LiquidityProviderSwapEvent.OutputTuple,
      LiquidityProviderSwapEvent.OutputObject
    >;
  };
}
