/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
import type { TreasuryFoundryArtifacts, FoundryArtifact } from './foundry-types';

// 导入 Foundry 生成的 JSON artifacts
import * as DefaultPoolOperator from '../out/DefaultPoolOperator.sol/DefaultPoolOperator.json';
import * as ZrxTreasury from '../out/ZrxTreasury.sol/ZrxTreasury.json';

/**
 * Treasury 包的 Foundry 原生 artifacts
 * 直接使用 Foundry JSON 格式，无需转换
 */
export const artifacts: TreasuryFoundryArtifacts = {
    ZrxTreasury: ZrxTreasury as FoundryArtifact,
    DefaultPoolOperator: DefaultPoolOperator as FoundryArtifact,
};
