/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
import type { TreasuryHardhatArtifacts, HardhatArtifact } from './hardhat-types';

// Import Hardhat artifacts
import * as ZrxTreasury from '../artifacts/contracts/src/ZrxTreasury.sol/ZrxTreasury.json';
import * as DefaultPoolOperator from '../artifacts/contracts/src/DefaultPoolOperator.sol/DefaultPoolOperator.json';
import * as DummyERC20Token from '../artifacts/contracts/src/DummyERC20Token.sol/DummyERC20Token.json';

/**
 * Treasury 包的 Hardhat artifacts
 * 使用 Hardhat 编译生成的 JSON 格式
 */
export const artifacts: TreasuryHardhatArtifacts = {
    ZrxTreasury: ZrxTreasury as any as HardhatArtifact,
    DefaultPoolOperator: DefaultPoolOperator as any as HardhatArtifact,
    DummyERC20Token: DummyERC20Token as any as HardhatArtifact,
};
