/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
import type { FoundryArtifact, FoundryArtifacts } from './foundry-types';

// 核心合约
import * as ZeroEx from '../out/ZeroEx.sol/ZeroEx.json';
import * as ZeroExOptimized from '../out/ZeroExOptimized.sol/ZeroExOptimized.json';
import * as IZeroEx from '../out/IZeroEx.sol/IZeroEx.json';
import * as FullMigration from '../out/FullMigration.sol/FullMigration.json';
import * as InitialMigration from '../out/InitialMigration.sol/InitialMigration.json';
import * as FlashWallet from '../out/FlashWallet.sol/FlashWallet.json';
import * as IFlashWallet from '../out/IFlashWallet.sol/IFlashWallet.json';

// Features
import * as BatchFillNativeOrdersFeature from '../out/BatchFillNativeOrdersFeature.sol/BatchFillNativeOrdersFeature.json';
import * as IBatchFillNativeOrdersFeature from '../out/IBatchFillNativeOrdersFeature.sol/IBatchFillNativeOrdersFeature.json';
import * as LiquidityProviderFeature from '../out/LiquidityProviderFeature.sol/LiquidityProviderFeature.json';
import * as ILiquidityProviderFeature from '../out/ILiquidityProviderFeature.sol/ILiquidityProviderFeature.json';
import * as MultiplexFeature from '../out/MultiplexFeature.sol/MultiplexFeature.json';
import * as IMultiplexFeature from '../out/IMultiplexFeature.sol/IMultiplexFeature.json';
import * as NativeOrdersFeature from '../out/NativeOrdersFeature.sol/NativeOrdersFeature.json';
import * as INativeOrdersFeature from '../out/INativeOrdersFeature.sol/INativeOrdersFeature.json';
import * as OtcOrdersFeature from '../out/OtcOrdersFeature.sol/OtcOrdersFeature.json';
import * as IOtcOrdersFeature from '../out/IOtcOrdersFeature.sol/IOtcOrdersFeature.json';
import * as OwnableFeature from '../out/OwnableFeature.sol/OwnableFeature.json';
import * as IOwnableFeature from '../out/IOwnableFeature.sol/IOwnableFeature.json';
import * as SimpleFunctionRegistryFeature from '../out/SimpleFunctionRegistryFeature.sol/SimpleFunctionRegistryFeature.json';
import * as ISimpleFunctionRegistryFeature from '../out/ISimpleFunctionRegistryFeature.sol/ISimpleFunctionRegistryFeature.json';
import * as TransformERC20Feature from '../out/TransformERC20Feature.sol/TransformERC20Feature.json';
import * as ITransformERC20Feature from '../out/ITransformERC20Feature.sol/ITransformERC20Feature.json';
import * as MetaTransactionsFeature from '../out/MetaTransactionsFeature.sol/MetaTransactionsFeature.json';
import * as MetaTransactionsFeatureV2 from '../out/MetaTransactionsFeatureV2.sol/MetaTransactionsFeatureV2.json';

// Transformers
import * as AffiliateFeeTransformer from '../out/AffiliateFeeTransformer.sol/AffiliateFeeTransformer.json';
import * as FillQuoteTransformer from '../out/FillQuoteTransformer.sol/FillQuoteTransformer.json';
import * as PayTakerTransformer from '../out/PayTakerTransformer.sol/PayTakerTransformer.json';
import * as PositiveSlippageFeeTransformer from '../out/PositiveSlippageFeeTransformer.sol/PositiveSlippageFeeTransformer.json';
import * as WethTransformer from '../out/WethTransformer.sol/WethTransformer.json';
import * as IERC20Transformer from '../out/IERC20Transformer.sol/IERC20Transformer.json';
import * as LogMetadataTransformer from '../out/LogMetadataTransformer.sol/LogMetadataTransformer.json';

// Bridge Adapters
import * as AvalancheBridgeAdapter from '../out/AvalancheBridgeAdapter.sol/AvalancheBridgeAdapter.json';
import * as BSCBridgeAdapter from '../out/BSCBridgeAdapter.sol/BSCBridgeAdapter.json';
import * as BaseBridgeAdapter from '../out/BaseBridgeAdapter.sol/BaseBridgeAdapter.json';
import * as CeloBridgeAdapter from '../out/CeloBridgeAdapter.sol/CeloBridgeAdapter.json';
import * as EthereumBridgeAdapter from '../out/EthereumBridgeAdapter.sol/EthereumBridgeAdapter.json';
import * as FantomBridgeAdapter from '../out/FantomBridgeAdapter.sol/FantomBridgeAdapter.json';
import * as OptimismBridgeAdapter from '../out/OptimismBridgeAdapter.sol/OptimismBridgeAdapter.json';
import * as PolygonBridgeAdapter from '../out/PolygonBridgeAdapter.sol/PolygonBridgeAdapter.json';

// Fee Collectors
import * as FeeCollector from '../out/FeeCollector.sol/FeeCollector.json';
import * as FeeCollectorController from '../out/FeeCollectorController.sol/FeeCollectorController.json';

/**
 * Foundry 原生的 artifacts 对象
 * 所有 artifacts 都直接使用 Foundry JSON 格式，不再转换为旧的 ContractArtifact 格式
 */
export const artifacts: FoundryArtifacts = {
    ZeroEx: ZeroEx as FoundryArtifact,
    ZeroExOptimized: ZeroExOptimized as FoundryArtifact,
    IZeroEx: IZeroEx as FoundryArtifact,
    FullMigration: FullMigration as FoundryArtifact,
    InitialMigration: InitialMigration as FoundryArtifact,
    FlashWallet: FlashWallet as FoundryArtifact,
    IFlashWallet: IFlashWallet as FoundryArtifact,
    BatchFillNativeOrdersFeature: BatchFillNativeOrdersFeature as FoundryArtifact,
    IBatchFillNativeOrdersFeature: IBatchFillNativeOrdersFeature as FoundryArtifact,
    LiquidityProviderFeature: LiquidityProviderFeature as FoundryArtifact,
    ILiquidityProviderFeature: ILiquidityProviderFeature as FoundryArtifact,
    MultiplexFeature: MultiplexFeature as FoundryArtifact,
    IMultiplexFeature: IMultiplexFeature as FoundryArtifact,
    NativeOrdersFeature: NativeOrdersFeature as FoundryArtifact,
    INativeOrdersFeature: INativeOrdersFeature as FoundryArtifact,
    OtcOrdersFeature: OtcOrdersFeature as FoundryArtifact,
    IOtcOrdersFeature: IOtcOrdersFeature as FoundryArtifact,
    OwnableFeature: OwnableFeature as FoundryArtifact,
    IOwnableFeature: IOwnableFeature as FoundryArtifact,
    SimpleFunctionRegistryFeature: SimpleFunctionRegistryFeature as FoundryArtifact,
    ISimpleFunctionRegistryFeature: ISimpleFunctionRegistryFeature as FoundryArtifact,
    TransformERC20Feature: TransformERC20Feature as FoundryArtifact,
    ITransformERC20Feature: ITransformERC20Feature as FoundryArtifact,
    MetaTransactionsFeature: MetaTransactionsFeature as FoundryArtifact,
    MetaTransactionsFeatureV2: MetaTransactionsFeatureV2 as FoundryArtifact,
    AffiliateFeeTransformer: AffiliateFeeTransformer as FoundryArtifact,
    FillQuoteTransformer: FillQuoteTransformer as FoundryArtifact,
    PayTakerTransformer: PayTakerTransformer as FoundryArtifact,
    PositiveSlippageFeeTransformer: PositiveSlippageFeeTransformer as FoundryArtifact,
    WethTransformer: WethTransformer as FoundryArtifact,
    IERC20Transformer: IERC20Transformer as FoundryArtifact,
    LogMetadataTransformer: LogMetadataTransformer as FoundryArtifact,
    AvalancheBridgeAdapter: AvalancheBridgeAdapter as FoundryArtifact,
    BSCBridgeAdapter: BSCBridgeAdapter as FoundryArtifact,
    BaseBridgeAdapter: BaseBridgeAdapter as FoundryArtifact,
    CeloBridgeAdapter: CeloBridgeAdapter as FoundryArtifact,
    EthereumBridgeAdapter: EthereumBridgeAdapter as FoundryArtifact,
    FantomBridgeAdapter: FantomBridgeAdapter as FoundryArtifact,
    OptimismBridgeAdapter: OptimismBridgeAdapter as FoundryArtifact,
    PolygonBridgeAdapter: PolygonBridgeAdapter as FoundryArtifact,
    FeeCollector: FeeCollector as FoundryArtifact,
    FeeCollectorController: FeeCollectorController as FoundryArtifact,
};
