/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace IERC20Transformer {
  export type TransformContextStruct = {
    sender: AddressLike;
    recipient: AddressLike;
    data: BytesLike;
  };

  export type TransformContextStructOutput = [
    sender: string,
    recipient: string,
    data: string
  ] & { sender: string; recipient: string; data: string };
}

export interface LogMetadataTransformerInterface extends Interface {
  getFunction(
    nameOrSignature: "deployer" | "die" | "transform"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "TransformerMetadata"): EventFragment;

  encodeFunctionData(functionFragment: "deployer", values?: undefined): string;
  encodeFunctionData(functionFragment: "die", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "transform",
    values: [IERC20Transformer.TransformContextStruct]
  ): string;

  decodeFunctionResult(functionFragment: "deployer", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "die", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "transform", data: BytesLike): Result;
}

export namespace TransformerMetadataEvent {
  export type InputTuple = [
    sender: AddressLike,
    taker: AddressLike,
    data: BytesLike
  ];
  export type OutputTuple = [sender: string, taker: string, data: string];
  export interface OutputObject {
    sender: string;
    taker: string;
    data: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LogMetadataTransformer extends BaseContract {
  connect(runner?: ContractRunner | null): LogMetadataTransformer;
  waitForDeployment(): Promise<this>;

  interface: LogMetadataTransformerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  deployer: TypedContractMethod<[], [string], "view">;

  die: TypedContractMethod<[ethRecipient: AddressLike], [void], "nonpayable">;

  transform: TypedContractMethod<
    [context: IERC20Transformer.TransformContextStruct],
    [string],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "deployer"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "die"
  ): TypedContractMethod<[ethRecipient: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transform"
  ): TypedContractMethod<
    [context: IERC20Transformer.TransformContextStruct],
    [string],
    "nonpayable"
  >;

  getEvent(
    key: "TransformerMetadata"
  ): TypedContractEvent<
    TransformerMetadataEvent.InputTuple,
    TransformerMetadataEvent.OutputTuple,
    TransformerMetadataEvent.OutputObject
  >;

  filters: {
    "TransformerMetadata(address,address,bytes)": TypedContractEvent<
      TransformerMetadataEvent.InputTuple,
      TransformerMetadataEvent.OutputTuple,
      TransformerMetadataEvent.OutputObject
    >;
    TransformerMetadata: TypedContractEvent<
      TransformerMetadataEvent.InputTuple,
      TransformerMetadataEvent.OutputTuple,
      TransformerMetadataEvent.OutputObject
    >;
  };
}
