/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */

// Import Hardhat artifacts
import * as ERC721Token from '../artifacts/contracts/src/ERC721Token.sol/ERC721Token.json';
import * as MintableERC721Token from '../artifacts/contracts/src/MintableERC721Token.sol/MintableERC721Token.json';
import * as IERC721Token from '../artifacts/contracts/src/interfaces/IERC721Token.sol/IERC721Token.json';
import * as IERC721Receiver from '../artifacts/contracts/src/interfaces/IERC721Receiver.sol/IERC721Receiver.json';

/**
 * ERC721 包的 Hardhat artifacts
 * 使用 Hardhat 编译生成的 JSON 格式
 */
export const artifacts = {
    ERC721Token: ERC721Token as any,
    MintableERC721Token: MintableERC721Token as any,
    IERC721Token: IERC721Token as any,
    IERC721Receiver: IERC721Receiver as any,
};
