"use strict";
/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.artifacts = void 0;
// Import Hardhat artifacts
const ERC721Token = __importStar(require("../artifacts/contracts/src/ERC721Token.sol/ERC721Token.json"));
const MintableERC721Token = __importStar(require("../artifacts/contracts/src/MintableERC721Token.sol/MintableERC721Token.json"));
const IERC721Token = __importStar(require("../artifacts/contracts/src/interfaces/IERC721Token.sol/IERC721Token.json"));
const IERC721Receiver = __importStar(require("../artifacts/contracts/src/interfaces/IERC721Receiver.sol/IERC721Receiver.json"));
/**
 * ERC721 包的 Hardhat artifacts
 * 使用 Hardhat 编译生成的 JSON 格式
 */
exports.artifacts = {
    ERC721Token: ERC721Token,
    MintableERC721Token: MintableERC721Token,
    IERC721Token: IERC721Token,
    IERC721Receiver: IERC721Receiver,
};
//# sourceMappingURL=artifacts.js.map