/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */

// Import Hardhat artifacts
import * as CallWithGas from '../artifacts/contracts/CallWithGas.sol/CallWithGas.json';
import * as SecurityCouncil from '../artifacts/contracts/SecurityCouncil.sol/SecurityCouncil.json';
import * as ZeroExProtocolGovernor from '../artifacts/contracts/ZeroExProtocolGovernor.sol/ZeroExProtocolGovernor.json';
import * as ZeroExTimelock from '../artifacts/contracts/ZeroExTimelock.sol/ZeroExTimelock.json';
import * as ZeroExTreasuryGovernor from '../artifacts/contracts/ZeroExTreasuryGovernor.sol/ZeroExTreasuryGovernor.json';
import * as ZeroExVotes from '../artifacts/contracts/ZeroExVotes.sol/ZeroExVotes.json';
import * as ZRXWrappedToken from '../artifacts/contracts/ZRXWrappedToken.sol/ZRXWrappedToken.json';
import * as IZeroExGovernor from '../artifacts/contracts/IZeroExGovernor.sol/IZeroExGovernor.json';
import * as IZeroExVotes from '../artifacts/contracts/IZeroExVotes.sol/IZeroExVotes.json';

/**
 * Governance 包的 Hardhat artifacts
 * 使用 Hardhat 编译生成的 JSON 格式
 */
export const artifacts = {
    CallWithGas: CallWithGas as any,
    SecurityCouncil: SecurityCouncil as any,
    ZeroExProtocolGovernor: ZeroExProtocolGovernor as any,
    ZeroExTimelock: ZeroExTimelock as any,
    ZeroExTreasuryGovernor: ZeroExTreasuryGovernor as any,
    ZeroExVotes: ZeroExVotes as any,
    ZRXWrappedToken: ZRXWrappedToken as any,
    IZeroExGovernor: IZeroExGovernor as any,
    IZeroExVotes: IZeroExVotes as any,
};