/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */

// Import Hardhat artifacts for test contracts
import * as DummyERC1155Receiver from '../artifacts/contracts/test/DummyERC1155Receiver.sol/DummyERC1155Receiver.json';

// Import production artifacts
import * as ERC1155 from '../artifacts/contracts/src/ERC1155.sol/ERC1155.json';
import * as ERC1155Mintable from '../artifacts/contracts/src/ERC1155Mintable.sol/ERC1155Mintable.json';
import * as MixinNonFungibleToken from '../artifacts/contracts/src/MixinNonFungibleToken.sol/MixinNonFungibleToken.json';
import * as IERC1155 from '../artifacts/contracts/src/interfaces/IERC1155.sol/IERC1155.json';
import * as IERC1155Mintable from '../artifacts/contracts/src/interfaces/IERC1155Mintable.sol/IERC1155Mintable.json';
import * as IERC1155Receiver from '../artifacts/contracts/src/interfaces/IERC1155Receiver.sol/IERC1155Receiver.json';

// Export artifacts directly as Hardhat format (compatible with ethers.js)
export const artifacts = {
    // Test contracts
    DummyERC1155Receiver: DummyERC1155Receiver,

    // Production contracts
    ERC1155: ERC1155,
    ERC1155Mintable: ERC1155Mintable,
    MixinNonFungibleToken: MixinNonFungibleToken,
    IERC1155: IERC1155,
    IERC1155Mintable: IERC1155Mintable,
    IERC1155Receiver: IERC1155Receiver,
};
