/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
import { ContractArtifact } from 'ethereum-types';

// Foundry artifacts import
import * as DummyERC20TokenFoundryArtifact from '../out/DummyERC20Token.sol/DummyERC20Token.json';
import * as DefaultPoolOperatorFoundryArtifact from '../out/DefaultPoolOperator.sol/DefaultPoolOperator.json';
import * as ZrxTreasuryFoundryArtifact from '../out/ZrxTreasury.sol/ZrxTreasury.json';

// Export artifacts
export const artifacts = {
    DummyERC20Token: DummyERC20TokenFoundryArtifact as any,
    DefaultPoolOperator: DefaultPoolOperatorFoundryArtifact as any,
    ZrxTreasury: ZrxTreasuryFoundryArtifact as any,
};

// Also export for compatibility
export const erc20Artifacts = {
    DummyERC20Token: DummyERC20TokenFoundryArtifact as any,
};
