/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
// Temporarily simplified for Foundry compatibility
// TODO: Add test-specific contracts as needed

import * as ZeroEx from '../out/ZeroEx.sol/ZeroEx.json';
import * as ZeroExOptimized from '../out/ZeroExOptimized.sol/ZeroExOptimized.json';
import * as IZeroEx from '../out/IZeroEx.sol/IZeroEx.json';
import * as FullMigration from '../out/FullMigration.sol/FullMigration.json';
import * as InitialMigration from '../out/InitialMigration.sol/InitialMigration.json';
import * as FlashWallet from '../out/FlashWallet.sol/FlashWallet.json';
import * as IFlashWallet from '../out/IFlashWallet.sol/IFlashWallet.json';

// Core Features
import * as BatchFillNativeOrdersFeature from '../out/BatchFillNativeOrdersFeature.sol/BatchFillNativeOrdersFeature.json';
import * as IBatchFillNativeOrdersFeature from '../out/IBatchFillNativeOrdersFeature.sol/IBatchFillNativeOrdersFeature.json';
import * as LiquidityProviderFeature from '../out/LiquidityProviderFeature.sol/LiquidityProviderFeature.json';
import * as ILiquidityProviderFeature from '../out/ILiquidityProviderFeature.sol/ILiquidityProviderFeature.json';
import * as MultiplexFeature from '../out/MultiplexFeature.sol/MultiplexFeature.json';
import * as IMultiplexFeature from '../out/IMultiplexFeature.sol/IMultiplexFeature.json';
import * as NativeOrdersFeature from '../out/NativeOrdersFeature.sol/NativeOrdersFeature.json';
import * as INativeOrdersFeature from '../out/INativeOrdersFeature.sol/INativeOrdersFeature.json';
import * as OtcOrdersFeature from '../out/OtcOrdersFeature.sol/OtcOrdersFeature.json';
import * as IOtcOrdersFeature from '../out/IOtcOrdersFeature.sol/IOtcOrdersFeature.json';
import * as OwnableFeature from '../out/OwnableFeature.sol/OwnableFeature.json';
import * as IOwnableFeature from '../out/IOwnableFeature.sol/IOwnableFeature.json';
import * as SimpleFunctionRegistryFeature from '../out/SimpleFunctionRegistryFeature.sol/SimpleFunctionRegistryFeature.json';
import * as ISimpleFunctionRegistryFeature from '../out/ISimpleFunctionRegistryFeature.sol/ISimpleFunctionRegistryFeature.json';
import * as TransformERC20Feature from '../out/TransformERC20Feature.sol/TransformERC20Feature.json';
import * as ITransformERC20Feature from '../out/ITransformERC20Feature.sol/ITransformERC20Feature.json';

// Transformers
import * as AffiliateFeeTransformer from '../out/AffiliateFeeTransformer.sol/AffiliateFeeTransformer.json';
import * as FillQuoteTransformer from '../out/FillQuoteTransformer.sol/FillQuoteTransformer.json';
import * as PayTakerTransformer from '../out/PayTakerTransformer.sol/PayTakerTransformer.json';
import * as PositiveSlippageFeeTransformer from '../out/PositiveSlippageFeeTransformer.sol/PositiveSlippageFeeTransformer.json';
import * as WethTransformer from '../out/WethTransformer.sol/WethTransformer.json';
import * as IERC20Transformer from '../out/IERC20Transformer.sol/IERC20Transformer.json';

// Bridge Adapters
import * as AvalancheBridgeAdapter from '../out/AvalancheBridgeAdapter.sol/AvalancheBridgeAdapter.json';
import * as BSCBridgeAdapter from '../out/BSCBridgeAdapter.sol/BSCBridgeAdapter.json';
import * as BaseBridgeAdapter from '../out/BaseBridgeAdapter.sol/BaseBridgeAdapter.json';
import * as CeloBridgeAdapter from '../out/CeloBridgeAdapter.sol/CeloBridgeAdapter.json';
import * as EthereumBridgeAdapter from '../out/EthereumBridgeAdapter.sol/EthereumBridgeAdapter.json';
import * as FantomBridgeAdapter from '../out/FantomBridgeAdapter.sol/FantomBridgeAdapter.json';
import * as OptimismBridgeAdapter from '../out/OptimismBridgeAdapter.sol/OptimismBridgeAdapter.json';
import * as PolygonBridgeAdapter from '../out/PolygonBridgeAdapter.sol/PolygonBridgeAdapter.json';

// Fee Collectors
import * as FeeCollector from '../out/FeeCollector.sol/FeeCollector.json';
import * as FeeCollectorController from '../out/FeeCollectorController.sol/FeeCollectorController.json';

export const artifacts = {
    ZeroEx: ZeroEx,
    ZeroExOptimized: ZeroExOptimized,
    IZeroEx: IZeroEx,
    FullMigration: FullMigration,
    InitialMigration: InitialMigration,
    FlashWallet: FlashWallet,
    IFlashWallet: IFlashWallet,
    BatchFillNativeOrdersFeature: BatchFillNativeOrdersFeature,
    IBatchFillNativeOrdersFeature: IBatchFillNativeOrdersFeature,
    LiquidityProviderFeature: LiquidityProviderFeature,
    ILiquidityProviderFeature: ILiquidityProviderFeature,
    MultiplexFeature: MultiplexFeature,
    IMultiplexFeature: IMultiplexFeature,
    NativeOrdersFeature: NativeOrdersFeature,
    INativeOrdersFeature: INativeOrdersFeature,
    OtcOrdersFeature: OtcOrdersFeature,
    IOtcOrdersFeature: IOtcOrdersFeature,
    OwnableFeature: OwnableFeature,
    IOwnableFeature: IOwnableFeature,
    SimpleFunctionRegistryFeature: SimpleFunctionRegistryFeature,
    ISimpleFunctionRegistryFeature: ISimpleFunctionRegistryFeature,
    TransformERC20Feature: TransformERC20Feature,
    ITransformERC20Feature: ITransformERC20Feature,
    AffiliateFeeTransformer: AffiliateFeeTransformer,
    FillQuoteTransformer: FillQuoteTransformer,
    PayTakerTransformer: PayTakerTransformer,
    PositiveSlippageFeeTransformer: PositiveSlippageFeeTransformer,
    WethTransformer: WethTransformer,
    IERC20Transformer: IERC20Transformer,
    AvalancheBridgeAdapter: AvalancheBridgeAdapter,
    BSCBridgeAdapter: BSCBridgeAdapter,
    BaseBridgeAdapter: BaseBridgeAdapter,
    CeloBridgeAdapter: CeloBridgeAdapter,
    EthereumBridgeAdapter: EthereumBridgeAdapter,
    FantomBridgeAdapter: FantomBridgeAdapter,
    OptimismBridgeAdapter: OptimismBridgeAdapter,
    PolygonBridgeAdapter: PolygonBridgeAdapter,
    FeeCollector: FeeCollector,
    FeeCollectorController: FeeCollectorController,
};
