/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IAuthorizable__factory } from "./IAuthorizable__factory";
export { IOwnable__factory } from "./IOwnable__factory";
